import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Neighbor Favor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/neighborfavor.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          welcome to neighbor favor!
        </h1>

        <p className={styles.description}>
          the coolest site on the internet (that is actually not on the internet)
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/login/" className={styles.card}>
            <h2>login page &rarr;</h2>
            <p>click here to log in!</p>
          </a>

          <a href="http://localhost:3000/signup/" className={styles.card}>
            <h2>sign up page &rarr;</h2>
            <p>click here to sign up!</p>
          </a>

          <a href="http://localhost:3000/main/" className={styles.card}>
            <h2>main page &rarr;</h2>
            <p>click here to go to the main page! even if you haven't logged in (it makes no sense)</p>
          </a>
  
        </div>
      </main>
    </div>
  )
}
